package goorm.nuto.Nuto.Exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum ErrorCode {
    INVALID_IMAGE(HttpStatus.UNSUPPORTED_MEDIA_TYPE, "INVALID_IMAGE"),
    INVALID_INPUT(HttpStatus.BAD_REQUEST, "INVALID_INPUT"),
    MISSING_REVIEW_TAG(HttpStatus.BAD_REQUEST, "MISSING_REVIEW_TAG"),
    EMAIL_NOT_VERIFIED(HttpStatus.FORBIDDEN, "EMAIL_NOT_VERIFIED"),
    NOT_FOUND_POST(HttpStatus.NOT_FOUND, "NOT_FOUND_POST"),
    NOT_FOUND_MEMBER(HttpStatus.NOT_FOUND, "NOT_FOUND_MEMBER"),
    NOT_FOUND_REVIEW(HttpStatus.NOT_FOUND, "NOT_FOUND_REVIEW"),
    NOT_FOUND_REVIEW_TAG(HttpStatus.NOT_FOUND, "NOT_FOUND_REVIEW_TAG"),
    NOT_FOUND_CHATROOM(HttpStatus.NOT_FOUND, "NOT_FOUND_CHATROOM"),
    DUPLICATE_PARTICIPANT(HttpStatus.CONFLICT, "DUPLICATE_PARTICIPANT"),
    DUPLICATE_REVIEW(HttpStatus.CONFLICT, "DUPLICATE_REVIEW"),
    DUPLICATE_REVIEW_TAG(HttpStatus.CONFLICT, "DUPLICATE_REVIEW_TAG"),
    DUPLICATE_EMAIL(HttpStatus.CONFLICT, "DUPLICATE_EMAIL"),
    DUPLICATE_NICKNAME(HttpStatus.CONFLICT, "DUPLICATE_NICKNAME"),
    REVIEW_ACCESS_DENIED(HttpStatus.UNAUTHORIZED, "REVIEW_ACCESS_DENIED"),
    INVALID_TOKEN(HttpStatus.UNAUTHORIZED, "INVALID_TOKEN"),
    IMAGE_SAVE_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "Internal Server Error"),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "INTERNAL_ERROR"),
    NOT_MEMBER_FOUND(HttpStatus.NOT_FOUND, "NOT_MEMBER_FOUND"),
    NOT_VERIFIED_EMAIL(HttpStatus.FORBIDDEN, "NOT_VERIFIED_EMAIL"),

    NOT_FOUND_CARD(HttpStatus.NOT_FOUND, "NOT_FOUND_CARD"),
    NOT_FOUND_CARDNUMBER(HttpStatus.NOT_FOUND, "NOT_FOUND_CARDNUMBER"),
    DUPLICATE_CARD(HttpStatus.CONFLICT, "DUPLICATE_CARD"),
    DUPLICATE_CARDNUMBER(HttpStatus.CONFLICT, "DUPLICATE_CARDNUMBER"),
    NOT_FOUND_CATEGORY(HttpStatus.NOT_FOUND, "NOT_FOUND_CATEGORY"),
    NOT_FOUND_RECEIPT(HttpStatus.NOT_FOUND, "NOT_FOUND_RECEIPT"),
    NOT_FOUND_INCOME(HttpStatus.NOT_FOUND, "NOT_FOUND_INCOME"),
    NOT_FOUND_CONSUME(HttpStatus.NOT_FOUND, "NOT_FOUND_CONSUME"),
    NOT_AUTHORIZED_RECEIPTACCESS(HttpStatus.UNAUTHORIZED, "NOT_AUTHORIZED_RECEIPTACCESS"),
    NOT_AUTHORIZED_CARDACCESS(HttpStatus.UNAUTHORIZED, "NOT_AUTHORIZED_CARDACCESS")
    ;

    private final HttpStatus status;
    private final String message;

    ErrorCode(HttpStatus staus, String internalError) {
        this.status = staus;
        this.message = internalError;
    }
}
